import os
import signal
import logging
import threading
import time
import random

from common import middleware, message_protocol, fruit_item

ID = int(os.environ["ID"])
MOM_HOST = os.environ["MOM_HOST"]
INPUT_QUEUE = os.environ["INPUT_QUEUE"]
SUM_AMOUNT = int(os.environ["SUM_AMOUNT"])
SUM_PREFIX = os.environ["SUM_PREFIX"]
SUM_CONTROL_EXCHANGE = "SUM_CONTROL_EXCHANGE"
SUM_CONTROL_EXCHANGE_KEY = "SUM_CONTROL"
AGGREGATION_AMOUNT = int(os.environ["AGGREGATION_AMOUNT"])
AGGREGATION_PREFIX = os.environ["AGGREGATION_PREFIX"]

# Control messages
class SumControl:
    EOF_RECV = 1

# Sum class
class SumFilter:
    def __init__(self):
        # Create fruit records queue
        self.input_queue = middleware.MessageMiddlewareQueueRabbitMQ(
            MOM_HOST, INPUT_QUEUE
        )

        # Create sums control exchanges
        self.control_exchange_sender = middleware.MessageMiddlewareExchangeRabbitMQ(MOM_HOST, SUM_CONTROL_EXCHANGE, [SUM_CONTROL_EXCHANGE_KEY])
        self.control_exchange_receiver = middleware.MessageMiddlewareExchangeRabbitMQ(MOM_HOST, SUM_CONTROL_EXCHANGE, [SUM_CONTROL_EXCHANGE_KEY])

        # Lock to control the last control message
        self.last_ctrl_message_lock = threading.Lock()
        self.last_ctrl_message = None

        # Lock to control input to avoid reading EOF message generated by itself
        self.eof_ctrl_generated_by_process_lock = threading.Lock()
        self.eof_ctrl_generated_by_process = False

        # Control to say if data was stored and sent
        self.data_was_sent = False

        # Lock to control de value of estimated clients
        self.estimated_clients_lock = threading.Lock()
        self.estimated_clients = 0

        # Create output exchanges
        self.data_output_exchanges = []
        for i in range(AGGREGATION_AMOUNT):
            data_output_exchange = middleware.MessageMiddlewareExchangeRabbitMQ(
                MOM_HOST, AGGREGATION_PREFIX, [f"{AGGREGATION_PREFIX}_{i}"]
            )
            self.data_output_exchanges.append(data_output_exchange)
        self.amount_by_fruit = {}

        # Assign signal handlers
        signal.signal(signalnum=signal.SIGTERM, handler=self._sigterm_handler)

        # Start and store control messages thread
        self.control_msg_input_thread = threading.Thread(target=self._read_control_message)
        self.control_msg_input_thread.start()

    def _read_control_message(self):
        logging.info(f"Input ctrl: start")
        INACTIVITY_TIMEOUT = 1.0
        self.keep_reading_ctrl = True

        while self.keep_reading_ctrl:
            logging.info(f"Input ctrl: start consuming")
            self.control_exchange_receiver.start_consuming(on_message_callback=self.__control_message_callback, inactivity_timeout=INACTIVITY_TIMEOUT)

    def __control_message_callback(self, message, ack, nack):
        try:
            if message is not None:
                ctrl_code = int(message)

                with self.last_ctrl_message_lock:
                    with self.eof_ctrl_generated_by_process_lock:

                        # Check if process created EOF message
                        if not self.eof_ctrl_generated_by_process and ctrl_code == SumControl.EOF_RECV:
                            self.last_ctrl_message = ctrl_code

                            with self.estimated_clients_lock:
                                self.estimated_clients += 1
                ack()
            elif not self.keep_reading_ctrl:
                self.control_exchange_receiver.stop_consuming()
        except:
            with self.last_ctrl_message_lock:
                self.last_ctrl_message = None
            nack()

        logging.info(f"Input ctrl: callback executed")


    def _process_data(self, fruit, amount):
        #logging.info(f"Process data")
        self.amount_by_fruit[fruit] = self.amount_by_fruit.get(
            fruit, fruit_item.FruitItem(fruit, 0)
        ) + fruit_item.FruitItem(fruit, int(amount))

    # Send data to aggregation stage
    def _send_data_to_aggregation(self):
        logging.info(f"Distribuiting data messages")
        # Get maximum length of chunk
        chunk_max_length = len(self.amount_by_fruit.values()) // AGGREGATION_AMOUNT

        # Set for initial sent data
        available_exchanges = set(range(0, AGGREGATION_AMOUNT))
        current_sent_data_total = 0
        exchange_idx = random.choice(tuple(available_exchanges))

        # For every piece of data
        for final_fruit_item in self.amount_by_fruit.values():
            # Reset output exchange settings for next exchange
            if current_sent_data_total == chunk_max_length:
                available_exchanges.remove(exchange_idx)
                exchange_idx = random.choice(tuple(available_exchanges))
                current_sent_data_total = 0

            # Send data
            self.data_output_exchanges[exchange_idx].send(
                message_protocol.internal.serialize(
                    [final_fruit_item.fruit, final_fruit_item.amount]
                )
            )
            current_sent_data_total += 1

        # Send EOFs
        logging.info(f"Broadcasting EOF message to aggregators")
        for data_output_exchange in self.data_output_exchanges:
            data_output_exchange.send(message_protocol.internal.serialize([]))

    # Process EOF
    # Sends EOF to the rest of the sums
    def _process_eof(self):
        logging.info(f"Process msg: EOF received")
        with self.eof_ctrl_generated_by_process_lock:
            self.control_exchange_sender.send(str(SumControl.EOF_RECV))
            self.eof_ctrl_generated_by_process = True
            self.last_ctrl_message = SumControl.EOF_RECV

            with self.estimated_clients_lock:
                self.estimated_clients += 1
        logging.info(f"Process msg: EOF stored")

    # Sigterm handler
    def _sigterm_handler(self, signum, frame):
        self.shutdown()

    def __get_shutdown_retry_backoff(self, current_retries):
        RETRY_SHUT_DOWN_TIME_SEC = 0.1
        return RETRY_SHUT_DOWN_TIME_SEC

    def process_data_messsage(self, message, ack, nack):

        # If timeout occurred
        if message is None:
            with self.last_ctrl_message_lock:
                # If a timeout occurred, then clients stopped sending data.
                # Otherwise, shutdown.
                if not self.data_was_sent:
                    if self.last_ctrl_message is SumControl.EOF_RECV:
                        logging.info(f"Process msg: send data to agg")
                        self._send_data_to_aggregation()
                        self.data_was_sent = True
                    else:
                        logging.info(f"Process msg: shutdown because of lost connection")
                        self.shutdown()
        else:
            # If a message is received, process it.
            fields = message_protocol.internal.deserialize(message)
            if len(fields) == 2:
                self._process_data(*fields)
            elif len(fields) == 0:
                self._process_eof(*fields)
            else:
                nack()
            ack()

    def shutdown(self):
        MAX_SHUTDOWN_RETRIES = 3
        current_retries = 0

        # Try up to MAX_SHUTDOWN_RETRIES
        while current_retries < MAX_SHUTDOWN_RETRIES:
            try:
                # Close input queue
                self.input_queue.close()

                logging.info(f"Input queue shutdown")

                # Close control messages input
                self.keep_reading_ctrl = False
                self.control_msg_input_thread.join()

                logging.info(f"Control msg input thread shutdown")

                # Close data outputs
                for data_output in self.data_output_exchanges:
                    data_output.close()

                logging.info(f"Successful shutdown")

            except:
                retry_time = self.__get_shutdown_retry_backoff(current_retries)
                time.sleep(retry_time)
                current_retries += 1

    CLIENTS_STOPPED_SENDING_DATA_SECS = 5.0

    def start(self):
        self.input_queue.start_consuming(self.process_data_messsage, inactivity_timeout=SumFilter.CLIENTS_STOPPED_SENDING_DATA_SECS)

def main():
    logging.basicConfig(level=logging.INFO)
    sum_filter = SumFilter()
    sum_filter.start()
    return 0


if __name__ == "__main__":
    main()
